
# Alacritty Cosmic-mint Theme

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#151c1a"
foreground = "#cde5dd"

[colors.cursor]
text = "CellBackground"
cursor = "#8fd6b3"
#cursor = "CellForeground"

[colors.normal]
black = "#0a1a1a"
red = "#e26d6d"
green = "#6dac95"
yellow = "#a9f1c6"
blue = "#3a7f76"
magenta = "#7daa97"
cyan = "#8fd6b3"
white = "#cde5dd"

[colors.bright]
black = "#102424"
red = "#e88b8b"
green = "#8fd6b3"
yellow = "#bff5d3"
blue = "#5aaea4"
magenta = "#a9f1c6"
cyan = "#cde5dd"
white = "#ffffff"
